### ISSUE TITLE
MessageEvent missing ReceivedAt timestamp

### ISSUE THREAD

**Issue by phillipCouto** [keighl/postmark#3]
Looks like you are missing the ReceivedAt field for the MessageEvent structure.

The [current documentation](http://developer.postmarkapp.com/developer-api-messages.html#outbound-message-details) has the field defined.

**Comment by phillipCouto** [comment]
I am more than happy to submit a PR for it.

**Comment by keighl** [comment]
Thanks for noticing this @phillipCouto. I appreciate it!

**Comment by phillipCouto** [comment]
Not a problem thanks for a great library! =)
