### ISSUE TITLE
json: cannot unmarshal string into Go struct field

### ISSUE THREAD

**Issue by phillipCouto** [keighl/postmark#4]
Looks like there is a bug in the library that is trying to json unmarshal an OutboundMessage.Attachment into the type postmark.Attachment.

The exact error message I am getting is ```json: cannot unmarshal string into Go struct field OutboundMessage.Attachments of type postmark.Attachment```

Let me know if you want me to provide more information or if you want I can submit a PR to fix this.

**Comment by keighl** [comment]
thanks @phillipCouto, a PR would be great!
