### ISSUE TITLE
Bump the version

### ISSUE THREAD

**Issue by phillipCouto** [keighl/postmark#7]
I have migrated my application to using the dep tool for package management and by default it detected the tag versions over using the master branch and forced my version of postmark to 1.1.1.

This version was missing the fix that was applied back in June and so to get things working again I had to use the master branch for the version. I know this library doesn't change that often but tagging a new version will help with stability in the future. This way major work could happen in the package and applications wouldn't be impacted unless they linked directly to the master branch instead of a tagged version.

**Comment by keighl** [comment]
Thanks for the reminder, @phillipCouto! Bumped to 1.1.2
